### ISSUE TITLE
Prediction results not using the input image?

### ISSUE THREAD

**Issue by syrfan12** [Li-Tong-621/DMID#1]
Thank you for the code and model you provided.
I have tried the model provided and tried to use my original image. The result is that the output image is an image that comes from the original dataset instead of my original image. I tried to modify the `noise` variable part and finally the result is the denoise result of my original image. Is it a bug or something wrong with what I did?

from
 ```
data_start = time.time() 
 b, c, h, w = noise.shape 
 clean = clean.to(device) 
 noise = noise.to(device)
```
become
```
 data_start = time.time() 
 b, c, h, w = noise.shape 
 noise = clean.to(device)
 clean = clean.to(device) 
```
https://github.com/Li-Tong-621/DMID/blob/2dd4b60c9c967fbb4ae144af85e2af1c72c440b2/main_for_real.py#L145-L152

**Comment by Li-Tong-621** [comment]
Hi, I'm glad that my work has caught your attention. 

In the current public code version (October 2023 or May 2023), we have only released the inference code that can reproduce the experiments mentioned in our paper. 
The current code only supports using your own images for Gaussian denoising. The code for denoising arbitrary real images will be made public later. 

Please refer to **main_for_gaussian.py** for implementation, and we look forward to seeing your results.
