### ISSUE TITLE
What if the denoised images you have are not natural images?

### ISSUE THREAD

**Issue by qianduodu** [Li-Tong-621/DMID#10]
Hello, I would like to train my own dataset. How should I train it?

**Comment by Li-Tong-621** [comment]
> Hello, I would like to train my own dataset. How should I train it?

Hello, I didn't understand your question. What do you mean by "train my own dataset"? Are you referring to training a diffusion model on your own dataset? DMID, an unsupervised denoising method, does not require training a diffusion model; instead, DMID directly uses OpenAI's pre-trained diffusion model, which is trained for generating srgb images.

**Comment by Li-Tong-621** [comment]
> Hello, I would like to train my own dataset. How should I train it?

Hi. 
If you wish to use DMID denoising on your own images or datasets, you can refer to the Tools section in the readme, which provides detailed steps. 

If you have specific questions, feel free to ask. 
If it helps, please give us a star~♥

**Comment by qianduodu** [comment]
Thank you for your reply. I really appreciate it.

**Comment by Li-Tong-621** [comment]
> Thank you for your reply. I really appreciate it.

No problem. Welcome to give us a star.

**Comment by Li-Tong-621** [comment]
What if the denoised images you have are not natural images?

1.You can first try to denoise directly with the current model. We also used non-natural image datasets in our paper, for example, the FMDD dataset, which is actually a dataset of fluorescent cell images. We treated the FMDD dataset as single-channel grayscale natural images, and you can refer to the code for specific operations.

2.You can also train a diffusion model with your own dataset. We used a model trained by OpenAI on ImageNet, and you can use OpenAI's code to train a generative model for polarized images. Some potential issues you might encounter can be found in the issue https://github.com/Li-Tong-621/DMID/issues/9.

**Comment by qianduodu** [comment]
You're very welcome. I'm glad I could help

**Comment by qianduodu** [comment]
Thank you so much for your reply.
