### ISSUE TITLE
Where is the training code for noise transformation of the embedding method？

### ISSUE THREAD

**Issue by Chuong98CC** [Li-Tong-621/DMID#11]
Hi Authors,
Thanks for releasing the code, I could not find the training code in the released version. 
Are you planing to release the code since it has been published for a year?
Thank you.

**Comment by Li-Tong-621** [comment]
> Hi Authors, Thanks for releasing the code, I could not find the training code in the released version. Are you planing to release the code since it has been published for a year? Thank you.

Hello, I didn't understand "training code". 

1. Are you referring to training a diffusion model on your own dataset? 

 **DMID, an unsupervised denoising method, does not require training a diffusion model**; instead, DMID directly uses OpenAI's pre-trained diffusion model, which is trained for generating srgb images.

2. OR if you want to denoise your own datasets or images?

You can follow the steps provided in "Tools" section of Readme.md, Some potential issues you might encounter can be found in the issues https://github.com/Li-Tong-621/DMID/issues/9 and https://github.com/Li-Tong-621/DMID/issues/10.

**Comment by Li-Tong-621** [comment]
Hello, may I ask if the issue has been resolved?


> Hi Authors, Thanks for releasing the code, I could not find the training code in the released version. Are you planing to release the code since it has been published for a year? Thank you.

**Comment by Chuong98CC** [comment]
Hi @Li-Tong-621 
Thanks for your reply. I still have a confusion about implementing the Embedding model. 
According to the paper, particularly in Equatorial Guinea (9), we need to train an AutoEncoder model, e.g $G_{\theta_1}$. Where is it implemented   in the source code? How are the Equ (11) to (16) implemented?

I really appreciate if you can help me clarify and understand more about your work. Thank you

**Comment by Li-Tong-621** [comment]
> Hi @Li-Tong-621 Thanks for your reply. I still have a confusion about implementing the Embedding model. According to the paper, particularly in Equatorial Guinea (9), we need to train an AutoEncoder model, e.g G θ 1 . Where is it implemented in the source code? How are the Equ (11) to (16) implemented?
> 
> I really appreciate if you can help me clarify and understand more about your work. Thank you

In python main_for_real_NT.py, line 262 "denoising" function.
If it is helpful, welcome to give us a star.
