### ISSUE TITLE
Whether the training code will be made public

### ISSUE THREAD

**Issue by runqi-zhao** [Li-Tong-621/DMID#2]
This is a very useful work, may I ask if the training code will be made public subsequently?

**Comment by Li-Tong-621** [comment]
Thank you for your interest!
Our paper is currently undergoing revisions, and we are enhancing the methodology further. The training code will be made publicly available in due course. Stay tuned for updates!

**Comment by runqi-zhao** [comment]
Thanks for the reply and have a great day!
