### ISSUE TITLE
Question About the Derivation of Formula 6

### ISSUE THREAD

**Issue by JiahuiYang01** [Li-Tong-621/DMID#5]
Hello, thank you for your outstanding contributions. I am confused about the derivation of formula 6. Can you explain why the derivation of this step is valid?
![img_v3_02dm_16f82162-3490-443c-89c3-15aa6213b25g](https://github.com/user-attachments/assets/a9a1b72d-c05c-49c5-94e7-adbcb42d4264)

**Comment by Li-Tong-621** [comment]
![Uploading 302f22eadfe11afbef66a7dc43a6b311.jpg…]()
If this was helpful, feel free to give a star.

**Comment by Li-Tong-621** [comment]
![302f22eadfe11afbef66a7dc43a6b311](https://github.com/user-attachments/assets/b771d305-bd77-4be5-85a0-1cd0465e3b55)
If this was helpful, feel free to give a star.

**Comment by JiahuiYang01** [comment]
Thank you for the quick response and the detailed, patient explanations.

**Comment by Li-Tong-621** [comment]
You're welcome, then I will close this issue.

**Comment by olex-ui** [comment]
Where can I find the supplementary material for the proof of the formulas？

**Comment by Li-Tong-621** [comment]
> Where can I find the supplementary material for the proof of the formulas？

website: https://ieeexplore.ieee.org/document/10607932/media#media
At "Supplemental Items"

If this was helpful, please give a star.

**Comment by olex-ui** [comment]
Thanks for your quick reply.
