### ISSUE TITLE
保存降噪结果与代码中的小bug

### ISSUE THREAD

**Issue by NSECUI** [Li-Tong-621/DMID#8]
作者你好，我想请问一下为什么我在复现代码的时候，虽然主程序完成了Finish!，但是文件夹里依然没有处理后的图片呢

**Comment by Li-Tong-621** [comment]
你好。
主程序完成了Finish!是指main_for_real_NT.py文件跑完了，出现了”noise transformation has finished!“，但是没有处理后的图片吗？

这是因为这个文件跑完保存的是pt文件，应该在results/nn**文件夹里面出现pt文件。

**Comment by Li-Tong-621** [comment]
我们之前在readme里面更新了一个比较详细的做法：
![1b8b7beb7bc02564ff8675cbc1d686bd](https://github.com/user-attachments/assets/1244b106-3b36-4a4e-aebc-f9869eb31247)

推荐可以先试试quick start，直接运行python main_for_gaussian.py，看看效果，能不能跑出图。

如果有帮助可以给我们点个赞。

**Comment by NSECUI** [comment]
![c8177c567eaba2c4a3f94b01892930f](https://github.com/user-attachments/assets/11671a21-eff3-4d72-91bc-c13d61d783a9)

**Comment by Li-Tong-621** [comment]
你好，可能是因为cv2不支持中文路径。

**Comment by NSECUI** [comment]
好的我再试试，感谢感谢

**Comment by Li-Tong-621** [comment]
按照这个图来说，
要么是因为cv2不支持中文路径。
要么是因为这个路径上面有没有建立的文件夹。

原来的代码如下：
os.makedirs('./results/'+option['data']['test_opt'],exist_ok=True)
os.makedirs('./results/'+option['data']['test_opt']+'/clean'  ,exist_ok=True)
os.makedirs('./results/'+option['data']['test_opt']+'/denoise',exist_ok=True)
option['save']['photo_path']='./results/'+option['data']['test_opt']+'/'
自动建立了保存的文件夹

但是这个图里面284行是你手改的路径。所以也有可能有这个文件夹没被建立的可能性。

> ![c8177c567eaba2c4a3f94b01892930f](https://private-user-images.githubusercontent.com/153263612/386845395-11671a21-eff3-4d72-91bc-c13d61d783a9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NjEyOTYsIm5iZiI6MTczMTc2MDk5NiwicGF0aCI6Ii8xNTMyNjM2MTIvMzg2ODQ1Mzk1LTExNjcxYTIxLWVmZjMtNGQ3Mi05MWJjLWMxM2Q2MWQ3ODNhOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNlQxMjQzMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNTFmZjBmYmFmNjBiMTYyOWFmMDkzNDllNDBmOTE0ZjNmMTU1YmRkNmIyOTA3YTZiMDQ4ODJkNTFhY2NlYzU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gwTPzxWIwXfdnvxYHBhhZtZhx5PCWwxC420YLIAVWaE)

**Comment by Li-Tong-621** [comment]
> 好的我再试试，感谢感谢

点个star吧 :blush:

**Comment by NSECUI** [comment]
您好，刚才点了那个星星了，刚才又重新试了试改成了英文路径还是不可以，好难受，我看那个文件夹生成了吧，再那一列有results，还有对应数据集对应的文件夹，但是文件夹里还是空的，里面没有去噪后的图片。麻烦大佬再指点一下呗，如果可以太感谢了，我是一个新手，不过感觉你们的想法很好，很想学习，真的想把它复现出来。

**Comment by Li-Tong-621** [comment]
> ```
>  您好，刚才点了那个星星了，刚才又重新试了试改成了英文路径还是不可以，好难受，我看那个文件夹生成了吧，再那一列有results，还有对应数据集对应的文件夹，但是文件夹里还是空的，里面没有去噪后的图片。麻烦大佬再指点一下呗，如果可以太感谢了，我是一个新手，不过感觉你们的想法很好，很想学习，真的想把它复现出来。
> ```

你好，可以先把代码都改回来：
![image](https://github.com/user-attachments/assets/4796ac4c-d4e7-4f01-8623-b8a733791f09)

直接运行python main_for_gaussian.py，然后发给我看看打印出来的option吗。

**Comment by NSECUI** [comment]
好的，好的我现在就去改，太感谢了

**Comment by NSECUI** [comment]
很抱歉这么晚还打扰您，我刚才又重新下载了一个新版按照您那个readme跑了一遍，这次什么都没有改只是按您readme里所说的将该放的东西放到了相对应的位置，然后开始复现您的代码，您的第一个虽然Quick Start跑通了，但是并没有出现那个保存的文件夹，跑您的第二个evaluation的时候并没有跑通。第一个图是跑Quick Start，第二三个图是跑evaluation。如果能得到您的指点就太感谢了。真的很想跑通，认真看了好久了。
![4cb7ff5fa9746d9b61aa036be358b79](https://github.com/user-attachments/assets/555d8134-1683-4c04-8330-ebc5fa755101)
![4c23732afec284a1a41098c49e0d540](https://github.com/user-attachments/assets/a4841d1b-9934-4125-a91e-6691aa4bcb57)
![c50846cb486edf7a2e51e6638fc1ace](https://github.com/user-attachments/assets/a8c986d7-34d7-469d-b54e-f349f36a8d72)

**Comment by Li-Tong-621** [comment]
> 很抱歉这么晚还打扰您，我刚才又重新下载了一个新版按照您那个readme跑了一遍，这次什么都没有改只是按您readme里所说的将该放的东西放到了相对应的位置，然后开始复现您的代码，您的第一个虽然Quick Start跑通了，但是并没有出现那个保存的文件夹，跑您的第二个evaluation的时候并没有跑通。第一个图是跑Quick Start，第二三个图是跑evaluation。如果能得到您的指点就太感谢了。真的很想跑通，认真看了好久了。 ![4cb7ff5fa9746d9b61aa036be358b79](https://private-user-images.githubusercontent.com/153263612/386858975-555d8134-1683-4c04-8330-ebc5fa755101.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NzI3MDgsIm5iZiI6MTczMTc3MjQwOCwicGF0aCI6Ii8xNTMyNjM2MTIvMzg2ODU4OTc1LTU1NWQ4MTM0LTE2ODMtNGMwNC04MzMwLWViYzVmYTc1NTEwMS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNlQxNTUzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZTY3MzBmOTA1NDcyNWVkM2E4YjE1ZWUzNDYwYzg3ODQ5YTQxZWZkZTgzNmIxYzk3NWNjY2FjZDQ2NzYzNTM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZOLLJ1COkWZQNGR24rk9syuqYCAoiDV8L1zxyDD7mkg) ![4c23732afec284a1a41098c49e0d540](https://private-user-images.githubusercontent.com/153263612/386858992-a4841d1b-9934-4125-a91e-6691aa4bcb57.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NzI3MDgsIm5iZiI6MTczMTc3MjQwOCwicGF0aCI6Ii8xNTMyNjM2MTIvMzg2ODU4OTkyLWE0ODQxZDFiLTk5MzQtNDEyNS1hOTFlLTY2OTFhYTRiY2I1Ny5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNlQxNTUzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMTJhZGIzYWViNzA0MTVjNjMyNTM2YzQxNTA3ZjBhZjIwYjAyNzMwNWJkNWZiY2Q0ZmMxMGRlMDg4Yjg5NGRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bpKOx1kYMexykxypU6kclM8MZ7J5SxQFPgjQAuIP8Jw) ![c50846cb486edf7a2e51e6638fc1ace](https://private-user-images.githubusercontent.com/153263612/386859007-a8c986d7-34d7-469d-b54e-f349f36a8d72.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NzI3MDgsIm5iZiI6MTczMTc3MjQwOCwicGF0aCI6Ii8xNTMyNjM2MTIvMzg2ODU5MDA3LWE4Yzk4NmQ3LTM0ZDctNDY5ZC1iNTRlLWYzNDlmMzZhOGQ3Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNlQxNTUzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMGNiYTFjYjA0YThhMDIyMDQ1Y2ZiODg1ZDIzMjc3NmY4NjM2OWNkZmViMzBiMTMyNjVlMjJjYzNlZmRhOTczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vV_cr6O0iu3tCIVirjzD43HvNm6j4k9-O9dD9sQ8y-I)

quick start应该能秒跑。
我发现quick start上次更新代码之后把默认的参数给错了。
gaussian的代码里面line248现在是：
parser.add_argument('--data_path', default='/data/litong/litong/Dataset/denoise_data/benchmark/McMaster', type=str, help='for example: ./data/Imagenet')
实际上应该是
parser.add_argument('--data_path', default='./data/McMaster', type=str, help='for example: ./data/Imagenet')

另外跟第二个问题也有关系的是：

line170应该从 ：
temp_denoise += self.sample_image(
                                                 x=data_transform(noise),
                                                 eta=eta,
                                                 difussion_times=difussion_times,
                                                 )
改为：
temp_denoise = self.sample_image(
                                                 x=data_transform(noise),
                                                 eta=eta,
                                                 difussion_times=difussion_times,
                                                 )




改完这个重新跑一下即可。
github上面代码也重新更新了。

**Comment by NSECUI** [comment]
好嘞，哥，我正在跑，目前看好像第一个没有什么问题了，太感谢了呜呜，好高兴。

**Comment by Li-Tong-621** [comment]
> 好嘞，哥，我正在跑，目前看好像第一个没有什么问题了，太感谢了呜呜，好高兴。

ok，不客气。欢迎之后引用我们的文章。

**Comment by NSECUI** [comment]
目前跑的evaluation是这样的，没有什么变换，可以问下哥您是这样的吗，跑的时候需要等一段时间吗。
![9e102025ddf80dcc02641bd91be8b9a](https://github.com/user-attachments/assets/acb3fd1c-c50a-4fcc-b479-3de928c9debc)

**Comment by NSECUI** [comment]
您放心，后期投文章一定会引用您的文章的哥

**Comment by Li-Tong-621** [comment]
> 目前跑的evaluation是这样的，没有什么变换，可以问下哥您是这样的吗，跑的时候需要等一段时间吗。 ![9e102025ddf80dcc02641bd91be8b9a](https://private-user-images.githubusercontent.com/153263612/386862111-acb3fd1c-c50a-4fcc-b479-3de928c9debc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NzQ2NzIsIm5iZiI6MTczMTc3NDM3MiwicGF0aCI6Ii8xNTMyNjM2MTIvMzg2ODYyMTExLWFjYjNmZDFjLWM1MGEtNGZjYy1iNDc5LTNkZTkyOGM5ZGViYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNlQxNjI2MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NmExOWE2MDhjMjY2MDJkMTY5MGYxM2MyZjdiZWM4MWIyNTFlNzJiNzRmYjY0MTcxYzY5YWJmMWFhNzcwNTQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.NVYLO1lxagA8MIwa-l_yl5cYzfwAjNLEk2X9vKkLcQA)

是需要等待的，按照evaluation的设置大部分图片都需要跑1000次左右迭代，所以要一定的时间。原来的代码里面没有print所以没有变化。你可以自己加几句print，就能看到跑到哪里了。

**Comment by NSECUI** [comment]
好的哥，谢谢您了，您早点休息，不打扰您了，真的非常感谢。

**Comment by NSECUI** [comment]
Tong哥我又来了，很抱歉再次打扰您，您的程序从昨天晚上我就再跑到现在，然后现在的结果是还在跑CBSD68这个数据集的test_sigma=25，但是我现在看已经去噪的图片，它似乎是有问题的，图片都是灰色的没有什么东西，您看下图，然后还有一个问题是我看到了test_sigma=15的68个图片，然后现在在跑CBSD68test_sigma=25这个情况下的图片，我没有在相关路径找到他们，不知道是什么原因，期待哥的回复，再次表示感谢。
![ff738ef50e487c3b055e7496650dd9e](https://github.com/user-attachments/assets/3c64f0ca-03dd-4688-9b92-cf9d0bb12821)

**Comment by Li-Tong-621** [comment]
> Tong哥我又来了，很抱歉再次打扰您，您的程序从昨天晚上我就再跑到现在，然后现在的结果是还在跑CBSD68这个数据集的test_sigma=25，但是我现在看已经去噪的图片，它似乎是有问题的，图片都是灰色的没有什么东西，您看下图，然后还有一个问题是我看到了test_sigma=15的68个图片，然后现在在跑CBSD68test_sigma=25这个情况下的图片，我没有在相关路径找到他们，不知道是什么原因，期待哥的回复，再次表示感谢。 ![ff738ef50e487c3b055e7496650dd9e](https://private-user-images.githubusercontent.com/153263612/386951515-3c64f0ca-03dd-4688-9b92-cf9d0bb12821.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4NDU5OTIsIm5iZiI6MTczMTg0NTY5MiwicGF0aCI6Ii8xNTMyNjM2MTIvMzg2OTUxNTE1LTNjNjRmMGNhLTAzZGQtNDY4OC05YjkyLWNmOWQwYmIxMjgyMS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QxMjE0NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMGQwY2U1MmM5ZTE2ZDA2NTJkZGVkNTRhMzU2YzA2NGVmNmIxNDY4YTczNDg0NzVlZTJiNjdkZTRiZGY2NWQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.CLe8Q0d5fkDlS8rDgvXIt949nod5mZIHnMvfJQwqQZs)

第一个问题： 图片不正常：把line180：从denoise = data_transform_reverse(denoise / eval_time).to(self.device)，改为denoise = data_transform_reverse(denoise).to(self.device)

第二个问题： 没有相关路径：每个数据集都保存在同一个路径了，每次都替换了。

两个问题都在github上面更改了。可以看一下新的gaussian的文件，以及sh文件。

**Comment by NSECUI** [comment]
收到！可以再问一下哥你是在什么设备上跑的么，用了多久的时间跑出来的，我现在用的我们组比较差的设备4060，从昨天跑到现在第一个数据集都没有跑完。

**Comment by Li-Tong-621** [comment]
> 收到！可以再问一下哥你是在什么设备上跑的么，用了多久的时间跑出来的，我现在用的我们组比较差的设备4060，从昨天跑到现在第一个数据集都没有跑完。

大部分在3090跑的。Urban这个数据集上的图像太大，在显存更大的卡上跑的。

不用一直都按照sh来跑，那个是为了得到尽量高的指标的。降低迭代次数，指标有所下降，但是跑的会很快。

**Comment by NSECUI** [comment]
好的，收到，了解了，非常感谢哥，感谢感谢，无以言表的感谢。
