### ISSUE TITLE
关于DMID拓展到其他类型的降噪任务

### ISSUE THREAD

**Issue by TiAmo-one** [Li-Tong-621/DMID#9]
作者你好，我的邮件名为一曲離歌﹌淚傾城，经过我的一顿操作，我似乎成功跑通了代码，接下来我详细的讲述一下遇见的问题以及待解决的疑惑

1.UNet模型不兼容导致的自己训练的ddpm无法导入
解决方法：
![屏幕截图 2024-12-02 171919](https://github.com/user-attachments/assets/71102ce0-d12e-4d4e-b19c-7862cf6f2bca)

2.没有clean图片的问题
解决方法：我仔细分析了代码之后发现干净图片似乎是用来计算图片生成质量的，我的数据集没有干净的图片，因此我把所有关于clean图片的代码全部删除了

待解决的疑惑：
1.我查看论文，无论DMID-p还是DMID-d，都不推荐R_T ，S_T同时设置为1，但是代码却默认同时为1
2.我想知道删除clean图片的代码是否可行？如果不能删除，我没有干净图片又该怎么办呢？
3.论文采用的DDIM去噪，但是我看代码居然跳步之后只生成一次，这是否太极端了一点？
4.我跑通代码之后生成的图片去噪效果极其惨淡，我想知道代码中具体有哪些参数可以调整，从而改变现状
5.我将同一张照片复制了20张，设置不同的noise_level(1,5,10,15.........80,85,90,95)，最后去噪的图片并没有太大的区别，这与我的参数设置有关吗？

**Comment by Li-Tong-621** [comment]
1. 代码默认同时为1是方便快速跑通代码，尤其是为了“Quick Start”。论文中的数据的超参数在evaluate.sh中提供了。

2. 删除clean图片的代码可行。DMID是自监督方法，不需要干净图片。之前在邮件中应该给了你另外的解决思路，就是把clean的路径传为noisy的路径（因为没有干净图片，最后也无法计算指标，所以传成noisy也可以）。

3. DMID允许遍历perception-distortion curve 。所以论文给出了两个版本指标DMID-d和DMID-p，就是为了给出两个最极端的指标值。
 We report the results of method labeled ”Ours-d” with least distortion, and a second method labeled “Ours-p” with greatest perceptual quality.  
DMID-d大部分的s_t取值为2，只生成一次中间结果。

4、5：跑的是什么代码？真实的还是高斯的？main_for_gaussian.py还是main_for_real.py？
推荐首先Quick Start，把代码跑通。然后尝试自己图片的高斯版本。最后再尝试拓展。

**Comment by HopeKite** [comment]
我使用的main_for_real.py，我所说的惨淡不是没效果，而是效果太猛了，我S_T只设置的1，图片有的内容就直接变白了，去噪后如图(左为原图)：
![image](https://github.com/user-attachments/assets/89e7fd06-e4b7-4659-8bac-dc91a0ad5f61)

可是我看您自带的FMDD数据集的去噪效果完全和这个不同，我在训练噪声转化pt的时候用的就是FMDD的参数
并且，如果S_T设置过大（我尝试设置为333），图片就全白了（悲~）
我感觉是不是我修改代码的时候删到大动脉上了，还是说针对我的数据真的就只有这效果

**Comment by Li-Tong-621** [comment]
可能是数据差距太大了，原来的模型可能完全不适合这个数据。

你可以试试用你修改后的代码跑原来的几个数据集的实验，看看其他的几个数据集跑出来的图片是否正常。如果其他数据集跑出来的图片正常，那就是代码没问题，可能是原来的模型实在不适合现在的数据。

**Comment by Li-Tong-621** [comment]
> 我使用的main_for_real.py，我所说的惨淡不是没效果，而是效果太猛了，我S_T只设置的1，图片有的内容就直接变白了，去噪后如图(左为原图)： ![image](https://private-user-images.githubusercontent.com/63900076/391522311-89e7fd06-e4b7-4659-8bac-dc91a0ad5f61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNDAwMTksIm5iZiI6MTczMzEzOTcxOSwicGF0aCI6Ii82MzkwMDA3Ni8zOTE1MjIzMTEtODllN2ZkMDYtZTRiNy00NjU5LThiYWMtZGM5MWEwYWQ1ZjYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDExNDE1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyZjdjZjdmNDJjMGIwNzM5NTI4MDUwZThhNzkxYzE2YThiYmQ3MDQyZTM2YzBlMTM4YTVmNWRmMjY2MTI0NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2hrax2LaY-NhqENP5FHGsaYWoGxpZAzpq96ho-cERuc)
> 
> 可是我看您自带的FMDD数据集的去噪效果完全和这个不同，我在训练噪声转化pt的时候用的就是FMDD的参数 并且，如果S_T设置过大（我尝试设置为333），图片就全白了（悲~） 我感觉是不是我修改代码的时候删到大动脉上了，还是说针对我的数据真的就只有这效果

可能是数据差距太大了，原来的模型可能完全不适合这个数据。

你可以试试用你修改后的代码跑原来的几个数据集的实验，看看其他的几个数据集跑出来的图片是否正常。如果其他数据集跑出来的图片正常，那就是代码没问题，可能是原来的模型实在不适合现在的数据。

**Comment by HopeKite** [comment]
很抱歉给您带来了一些困扰，经过我的验证，发现确实是我修改代码时出现了错误导致的错误的结果，现在我使用原始代码只修改参数和必须部分被修改的代码(如UNet模型的兼容问题)，应该是得到了正确的结果，左为原图（可能不太明显但确实有效果）：
![image](https://github.com/user-attachments/assets/ef05e2ca-0890-4e3d-a07f-c75ae5749221)
由衷的感谢您的帮助

**Comment by Li-Tong-621** [comment]
> 很抱歉给您带来了一些困扰，经过我的验证，发现确实是我修改代码时出现了错误导致的错误的结果，现在我使用原始代码只修改参数和必须部分被修改的代码(如UNet模型的兼容问题)，应该是得到了正确的结果，左为原图（可能不太明显但确实有效果）： ![image](https://private-user-images.githubusercontent.com/63900076/393185238-ef05e2ca-0890-4e3d-a07f-c75ae5749221.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NzgxMzgsIm5iZiI6MTczMzQ3NzgzOCwicGF0aCI6Ii82MzkwMDA3Ni8zOTMxODUyMzgtZWYwNWUyY2EtMDg5MC00ZTNkLWEwN2YtYzc1YWU1NzQ5MjIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA5MzcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2NmVjMDkzZjRhMzRhMTU5NjAyMjg0MDFiZWUyMDE4MGYwYmU1Yzc4ZDlkMjEwNTUxYjc2Y2FmMjQxY2ZkMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.q3bi-SsJHbOgNRhpWA93AK90NZN_GboUhQ_tHFH-B9E) 由衷的感谢您的帮助

不客气。降噪能力与噪声转换时传入的参数、降噪时使用的UNet都有关。可以尝试寻找一个适合的噪声转换的参数，更强力或者更适合当前任务的Unet。
